version: '3.8'
services:
  keycloak:
    build: ./keycloak
    container_name: keycloak-app
    ports:
      - "8080:8080"
    tty: true
    stdin_open: true
  db:
    build: ./database
    container_name: db
    ports:
      - "5432:5432"
    tty: true
    stdin_open: true